#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import is_refs_section, parse_deck_outline, parse_notes, slide_title_key

W = Inches(13.333)
H = Inches(7.5)
NAVY = RGBColor(0x1A, 0x2B, 0x4A)
BLUE = RGBColor(0x00, 0x66, 0xCC)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
LIGHT = RGBColor(0xF7, 0xF8, 0xFA)
GRAY = RGBColor(0x66, 0x66, 0x66)


def add_textbox(slide, x, y, w, h, text, size=18, bold=False, color=NAVY, align=PP_ALIGN.LEFT):
    tb = slide.shapes.add_textbox(x, y, w, h)
    tf = tb.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = align
    r = p.add_run()
    r.text = text
    r.font.size = Pt(size)
    r.font.bold = bold
    r.font.color.rgb = color
    r.font.name = 'Arial'
    return tb


def set_bg(slide, color):
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = color


def add_notes(slide, text: str):
    tf = slide.notes_slide.notes_text_frame
    tf.text = text


def cover(prs: Presentation, title: str, notes: str | None):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    set_bg(slide, NAVY)
    bar = slide.shapes.add_shape(1, 0, 0, W, Inches(0.08))
    bar.fill.solid()
    bar.fill.fore_color.rgb = BLUE
    bar.line.fill.background()
    add_textbox(slide, Inches(0.9), Inches(2.2), Inches(10.8), Inches(1.2), title, size=28, bold=True, color=WHITE)
    add_textbox(
        slide,
        Inches(0.9),
        Inches(3.4),
        Inches(8.0),
        Inches(0.5),
        'Generated by research_writer skill',
        size=14,
        color=WHITE,
    )
    add_notes(slide, notes or f'封面页：{title}')


def content_slide(prs: Presentation, title: str, bullets: list[str], notes: str | None):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    set_bg(slide, WHITE)
    bar = slide.shapes.add_shape(1, 0, 0, W, Inches(0.06))
    bar.fill.solid()
    bar.fill.fore_color.rgb = BLUE
    bar.line.fill.background()
    add_textbox(slide, Inches(0.8), Inches(0.5), Inches(11.5), Inches(0.6), title, size=22, bold=True)
    y = Inches(1.4)
    for bullet in bullets[:6]:
        dot = slide.shapes.add_shape(1, Inches(0.9), y + Inches(0.08), Inches(0.08), Inches(0.08))
        dot.fill.solid()
        dot.fill.fore_color.rgb = BLUE
        dot.line.fill.background()
        add_textbox(slide, Inches(1.1), y, Inches(11.0), Inches(0.45), bullet, size=14, color=NAVY)
        y += Inches(0.65)
    if notes:
        add_notes(slide, notes)


def refs_slide(prs: Presentation, title: str, bullets: list[str], notes: str | None):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    set_bg(slide, LIGHT)
    add_textbox(slide, Inches(0.8), Inches(0.5), Inches(11.5), Inches(0.6), title, size=22, bold=True)
    y = Inches(1.3)
    for idx, bullet in enumerate(bullets[:10], 1):
        add_textbox(slide, Inches(0.9), y, Inches(11.4), Inches(0.38), f'{idx}. {bullet}', size=11, color=GRAY)
        y += Inches(0.42)
    if notes:
        add_notes(slide, notes)


def lookup_notes(notes_map: dict[str, str], slide_title: str) -> str | None:
    key = slide_title_key(slide_title)
    if key in notes_map:
        return notes_map[key]
    for k, v in notes_map.items():
        if k.lower() == key.lower():
            return v
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description='Generate PPT from deck-outline and speaker notes')
    parser.add_argument('--deck', required=True, help='path to deck-outline.md')
    parser.add_argument('--notes', required=False, help='path to speaker-notes.md')
    parser.add_argument('--output', required=True)
    parser.add_argument('--title', default=None, help='cover title override')
    args = parser.parse_args()

    deck_text = Path(args.deck).read_text(encoding='utf-8')
    slides = parse_deck_outline(deck_text)
    if not slides:
        print('No slides found in deck-outline.md', file=__import__('sys').stderr)
        return 1

    notes_map: dict[str, str] = {}
    if args.notes and Path(args.notes).exists():
        notes_map = parse_notes(Path(args.notes).read_text(encoding='utf-8'))

    cover_title = args.title or slide_title_key(slides[0]['title'])
    cover_notes = lookup_notes(notes_map, slides[0]['title'])

    prs = Presentation()
    prs.slide_width = W
    prs.slide_height = H
    cover(prs, cover_title, cover_notes)

    for slide in slides[1:]:
        title = slide_title_key(slide['title'])
        bullets = slide['bullets']
        notes = lookup_notes(notes_map, title)
        if is_refs_section(title):
            refs_slide(prs, title, bullets, notes)
        else:
            content_slide(prs, title, bullets, notes)

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    prs.save(str(out))
    print(f'PPT generated: {out}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
